### ISSUE TITLE
ContactCard component

### ISSUE THREAD

**Issue by ipeglin** [et-dagen/et-dagen#105]
**Describe the solution you'd like**
I want a nice ContactCard that should display an image of a board member, as well as name, position and contact information. The information that should be displayed:
* Name
* Image
* Position
* Email
* Phone number

It might be ok to simply hard code in the information. If not, we have to upload everything to Firebase as well.

**Functionality**
`mailto:` for clicking email
`tel:` for clicking phone number

**Comment by AasmundN** [comment]
Think we can pass in the information as props for now, and then expand so the information is fetched from the database later.
