### ISSUE TITLE
Event management API endpoints

### ISSUE THREAD

**Issue by ipeglin** [et-dagen/et-dagen#111]
**Describe the solution you'd like**
Set up endpoints for administration of events. This admin UI should only be available for users of type `admin` og `company`. _**NB! Company users should only be able to modify events that correspond to their own companyUID.**_

**Suggested Event type**
```ts
type EventType = 'presentation' | 'dinner' | null
Event: {
  capacity: number | string // string must be 'null' if not limited event
  companyUID: string // Company hosting the event
  date: {
    end: string // ISO 8601 Datetime string
    start: string // ISO 8601 Datetime string. Format: YYYY-MM-DDThh:mm:ssZ
  }
  description: string // Should this be a string rendered to a span, or should this be markup in HTML?
  location: {
    map: string // URL for map navigation. I.e. Mazemap or Google maps
    name: string // Location name
  }
  title: string // Event title
  type: EventType // Possibly `presentation`, `dinner` or `null`?
}
```

**Functionality**
* Create new events
* Edit event information *
* Delete events *
\*(if `company` user: only for your own company)

**Comment by JStoresund** [comment]
A few notes in regards to the comment written by @ipeglin . I changed the *name* parameter to be called *title*. Additionally, the *type* parameter is called *eventtype*, and is either 'presentation', 'dinner' or 'other'. The only optional parameter is endtime.

**Comment by ipeglin** [comment]
I updated the type of Event in the description to match the now implemented timeline component. This is just so everything should run smoothly. You can absolutely add other parameters if neccessary
