### ISSUE TITLE
Refactor HomeBanner to CompanyHero format

### ISSUE THREAD

**Issue by ipeglin** [et-dagen/et-dagen#163]
### Describe the bug
The HomeBanner component is not appropriately responsive. This should hold a similar responsive attributes as the CompanyHero component.

### Expected behavior
Same resposiveness as CompanyHero, but consider to not render image when reaching `xs` breakpoint. Also. Increase banner height to make landing page banner more spacious and modern.

### Screenshots
Too narrow between text and image. Should be more spacious like CompanyHero:
![image](https://github.com/et-dagen/et-dagen/assets/26115581/033f5721-f93c-42a0-8f3b-c89912984184)

Almost overlaps, instead of stacking:
![image](https://github.com/et-dagen/et-dagen/assets/26115581/289bf559-99da-4fba-bc38-f03f64559d44)

Too narrow height on HomeBanner component. Especially when not rendering the image:
![image](https://github.com/et-dagen/et-dagen/assets/26115581/0787c700-b6be-435f-818d-ba3f905a022c)

**Comment by AasmundN** [comment]
Keep in mind that there should be some space for the countdown. Maybe postpone working on this until the countdown is merged.
