### ISSUE TITLE
Jobs page

### ISSUE THREAD

**Issue by AasmundN** [et-dagen/et-dagen#171]
### Is your feature request related to a problem? Please describe.

Jobs list with simple sorting and filtering at /jobs

**Comment by ipeglin** [comment]
We should probably also implement the /jobs/:id page right away, to provide a "clean" page where the user can read the info. I think they would appreciate not having to deal with obstructions and distractions from other jobs (or having to deal with ugly and narrow modals).

**Comment by AasmundN** [comment]
Yeah that's what I'm thinking
