### ISSUE TITLE
Always perserve localePath

### ISSUE THREAD

**Issue by ipeglin** [et-dagen/et-dagen#224]
### Is your feature request related to a problem? Please describe.

Always perserve locale path for navigation link. Change all `navigateTo(your_link)` to `navigateTo(localePath(your_link))`.

**Comment by ranerhei** [comment]
Encountered a error on some pages: Argument of type 'LocalePathFunction' is not assignable to parameter of type 'RouteLocationRaw | null | undefined'.

**Comment by ipeglin** [comment]
> Encountered a error on some pages: Argument of type 'LocalePathFunction' is not assignable to parameter of type 'RouteLocationRaw | null | undefined'.

Where did these errors occur? Can you give a specific line of code that causes the error, so I can troubleshoot the issue?
