### ISSUE TITLE
Throw error on incorrect event datetime

### ISSUE THREAD

**Issue by ipeglin** [et-dagen/et-dagen#238]
### Describe the bug

When editing or creating event with event start `datetime` **after** end `datetime`, the server should throw an error. The current solution is not returning any errors, resulting in the appearance of being a successful operation, even though the event has not been updated.

### To Reproduce

1. Go to `/event/edit/[id]`
2. Modify start time to a timestamp later than end time.
4. Click **Save changes**
5. See success message
6. Go to `/program`
7. See unchanged event

**Comment by JStoresund** [comment]
Interesting. I assumed lines 55-59 took care of that, but it's apparently not working.
