### ISSUE TITLE
Create locale-switcher component

### ISSUE THREAD

**Issue by ipeglin** [et-dagen/et-dagen#32]
Create a components for switching locales. This may be places in a lower corner (absolute positioning in layout) on the website. Should hold option-like select type to choosing between languages. 

A good start might be to checkout:
1. i18n docs for [Lang Switcher](https://v8.i18n.nuxtjs.org/guide/lang-switcher) with examples
2. Nuxt docs for [components  and file structure](https://nuxt.com/docs/guide/directory-structure/components)

Additional features that may be suitable:
- Flags corresponding to the language or accent. I.E:
> - 🇳🇴 Norsk
> - 🇬🇧 English
> - 🇺🇸 English (United States)

**Comment by AasmundN** [comment]
See #66. The locale switcher will be placed in the navbar, and should use the `VMenu` component from _Vuetify_, similar to the `UserButton` implemented in the same PR.
