### ISSUE TITLE
i18n locales from files

### ISSUE THREAD

**Issue by AasmundN** [et-dagen/et-dagen#49]
Looks like this might be caused by `vue-i18n`, one of the dependecies of `@nuxtjs/i18n`: https://github.com/nuxt-modules/i18n/issues/2300

**Comment by ipeglin** [comment]
Ser det er folk som har kommet med workaround ved å override i18n...

Ref.
```
Thanks I fixed it for now by setting `"overrides": {
    "vue-i18n": "9.3.0-beta.24"
  }` in package.json

_Originally posted by @Me-Phew in https://github.com/nuxt-modules/i18n/issues/2300#issuecomment-1674881669_
```

Var også noen lenger oppe i kommentarfeltet som nevnte at man ikke fikk det samme problemet om man brukte yarn? Hadde i så fall vært en enkelt fix det da. Burde kanskje teste det ut? Eller kanskje enda bedre, hvis det funker med pnpm

**Comment by ipeglin** [comment]
Sounds good. If I remember correctly; pnpm uses the npm package distribution  under to hood, so not quite sure why is would work with one, and not the other. However, I prefer pnpm over npm 10 out of 10 times as I dont need to download duplicates of the same packages every other week :)
