### ISSUE TITLE
Hello, Developer!

### ISSUE THREAD

**Issue by ipeglin** [et-dagen/et-dagen#59]
**Is your feature request related to a problem? Please describe.**
A new page which route is corresponding to your name, i.e. Philip creates the page `/philip`. In this page, you should write some TypeScript (TS) that stores your name, age, and perhaps some info about yourself. These variables should be displayed in your browser (use them in the <template></template>) using the variable {{ variableName }} syntax.

Also. Output the information in a cool format in to your console.

(Optional) Play around with some styling.

**Additional context**
Starting template:
```vue
<script setup lang="ts">
  // Your TS here
</script>

<template>
  <div>
    <h1>Your content here</h1>
  </div>
</template>

<style>

</style>
```

**Comment by AasmundN** [comment]
Play around with some Vuetify components too.
