### ISSUE TITLE
Job Advertisement page gives `Server Error (500)` upon company UUID mismatch in DB

### ISSUE THREAD

**Issue by ipeglin** [et-dagen/et-dagen#62]
## **Describe the bug**
When `company_uuid` property in the Firebase database is mismatched with the ID of the company stored in the appropriate collection, the server throws an error code 500. This results in a non-functioning `/job_advertisements/job_advertisements` route.

**NB! This error still occurs even though the visible_bool is set to false. Therefore this issue has to be addressed.**

## **To Reproduce**

1. Go to Firebase Database console
2. Expand `job_advertisements`
3. Modify any entry's `company_uuid` value by any number of characters
4. Refresh [etdagen](etdagen.no/job_advertisements/job_advertisements)
5. See error

## **Expected behavior**
Any advertisements with a mismatch in `company_uuid` should not be rendered, and/or the server should respond with appropriate errors (which of course is handled in a proper manor in the front-end)

### Error
![image](https://github.com/et-dagen/et-dagen/assets/26115581/9dc0c2c1-3c1d-4eb9-80b5-1b0a0fa77125)

![image](https://github.com/et-dagen/et-dagen/assets/26115581/a972a081-2a16-438a-84e1-53b3fa5d5a81)

### Expected behavior
![image](https://github.com/et-dagen/et-dagen/assets/26115581/9cd60edf-a3dd-402d-9ce8-21e800b04f26)

![image](https://github.com/et-dagen/et-dagen/assets/26115581/dbc0cb60-b103-428a-b2c0-c18762775380)

**Comment by ipeglin** [comment]
NB! This error still occurs even though the `visible_bool` is set to `false`. Therefore this issue has to be addressed.

**Comment by AasmundN** [comment]
I will close this as it is not related to this repo.

**Comment by AasmundN** [comment]
I will close this as it is not related to this repo.
